test_data:
  directory: "data/raw/Test"
  img_height: 224
  img_width: 224
  batch_size: 64
  class_mode: "binary"

models_to_evaluate:
    # - name: "DenseNet Model"
    #   path: "densenet_final.keras"

    # - name: "Resnet Model"
    #   path: "resnet_final.keras"

    # - name: "Xception Model"
    #   path: "xception_final.keras"

    - name: "Ensemble Model"
      path: "ensemble_final.keras"

metrics:
  threshold: 0.5
