
# ResNet training config
epochs: 20
batch_size: 64
input_shape: [224, 224, 3]
optimizer: "adam"
learning_rate: 0.0001
loss: "binary_crossentropy"
metrics:
  - "accuracy"

augmentation:
  shear_range: 0.1
  zoom_range: 0.2
  horizontal_flip: true
  rotation_range: 15
  brightness_range: [0.8, 1.2]

validation_split: 0.2

early_stopping:
  monitor: "val_loss"
  patience: 5

reduce_lr_on_plateau:
  monitor: "val_loss"
  factor: 0.1
  patience: 3
  min_lr: 0.00001

output_dirs:
  logs: "experiments/individual_models/resnet/logs"
  checkpoints: "experiments/individual_models/resnet/checkpoints"
  results: "experiments/individual_models/resnet/results"
